# netlify.toml

[build]
  command = "npm install"
  # publish = "dist" # Removed publish directory setting
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

# [build.environment]
#   NODE_VERSION = "18"

